apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /nfs/django
    server: nfs.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-claim
  namespace: ${NAMESPACE}
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
