# Generated by Django 2.0.1 on 2018-01-17 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'артист', 'verbose_name_plural': 'артисты'},
        ),
        migrations.AddField(
            model_name='genre',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='дата выхода'),
        ),
    ]
