# Generated by Django 2.0.1 on 2018-01-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('data_of_career', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'артист',
                'verbose_name_plural': 'артисты',
                'ordering': ('-data_of_career',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('album', models.ManyToManyField(related_name='tracks', to='app1.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracks', to='app1.Artist', verbose_name='Артист')),
                ('genre', models.ManyToManyField(related_name='tracks', to='app1.Genre')),
            ],
            options={
                'verbose_name': 'трек',
                'verbose_name_plural': 'треки',
            },
        ),
    ]
