# Generated by Django 2.0.1 on 2018-01-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180118_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ManyToManyField(related_name='tracks_of_album', to='app1.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracks_of_artist', to='app1.Artist', verbose_name='Артист'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ManyToManyField(related_name='tracks_of_genre', to='app1.Genre'),
        ),
    ]
